In [53]:
import pandas as pd
import numpy as np
import sqlite3

In [2]:
df = pd.read_csv('raw_sales_data.csv')
print(df)

     Transaction_ID Product_Name        Price  Quantity        Date
0            1000.0   HEADPHONES   539.187392       4.0  11/05/2026
1            1001.0   smartphone   299.148021       4.0  2026-04-03
2            1002.0     charger    126.239849       5.0  2026-06-21
3            1003.0   SmartWatch   231.696207       8.0  2026-01-24
4            1004.0   smartphone  1122.517587       5.0  2026-03-01
..              ...          ...          ...       ...         ...
195          1195.0     charger    668.631629       1.0  2026-03-25
196          1196.0      Laptop    210.328599       5.0  2026-05-10
197          1197.0   smartphone          NaN       2.0  2026-03-11
198          1198.0   smartphone          NaN       6.0  2026-05-25
199          1199.0      Laptop    584.238547       1.0  2026-05-03

[200 rows x 5 columns]

In [3]:
print(df.isnull().sum())

Transaction_ID    8
Product_Name      0
Price             8
Quantity          6
Date              7
dtype: int64

In [5]:
print(df.duplicated().sum())

0

In [7]:
print(df.head(10))

   Transaction_ID Product_Name        Price  Quantity        Date
0          1000.0   HEADPHONES   539.187392       4.0  11/05/2026
1          1001.0   smartphone   299.148021       4.0  2026-04-03
2          1002.0     charger    126.239849       5.0  2026-06-21
3          1003.0   SmartWatch   231.696207       8.0  2026-01-24
4          1004.0   smartphone  1122.517587       5.0  2026-03-01
5          1005.0   SmartWatch   771.350654       8.0  2026-05-02
6          1006.0   HEADPHONES   627.285065       1.0  2026-05-11
7          1007.0   HEADPHONES   793.676924       9.0  2026-05-28
8          1008.0      Laptop    531.272385       6.0  2026-02-15
9          1009.0     charger    880.096590       3.0  2026-01-15

In [8]:
df.dropna(subset=['Transaction_ID'], inplace=True) # it will drop all rows that have nan values in transaction_id column

In [15]:
print(df.isnull().sum())

Transaction_ID    0
Product_Name      0
Price             8
Quantity          6
Date              7
dtype: int64

In [ ]:
#=============================
#  CLEANING TRANSACTION_IS 
#=============================

In [11]:
df.drop_duplicates(subset=['Transaction_ID'], keep='first', inplace=True)

In [12]:
print(df)

     Transaction_ID Product_Name        Price  Quantity        Date
0            1000.0   HEADPHONES   539.187392       4.0  11/05/2026
1            1001.0   smartphone   299.148021       4.0  2026-04-03
2            1002.0     charger    126.239849       5.0  2026-06-21
3            1003.0   SmartWatch   231.696207       8.0  2026-01-24
4            1004.0   smartphone  1122.517587       5.0  2026-03-01
..              ...          ...          ...       ...         ...
195          1195.0     charger    668.631629       1.0  2026-03-25
196          1196.0      Laptop    210.328599       5.0  2026-05-10
197          1197.0   smartphone          NaN       2.0  2026-03-11
198          1198.0   smartphone          NaN       6.0  2026-05-25
199          1199.0      Laptop    584.238547       1.0  2026-05-03

[188 rows x 5 columns]

In [14]:
# print(df['Transaction_ID'].duplicated().sum())

0

In [16]:
#=========================
#    CLEANIING PRICES 
#=========================

In [21]:
df['Price'] = np.where(df['Price'] == -999.0, np.nan, df['Price']) #np.where(condition, if_true, if_false)

In [24]:
mean_price = df['Price'].mean()

In [25]:
df['Price'] = df['Price'].fillna(mean_price) # fill nan values with mean of prices

In [42]:
df['Price'] = df['Price'].round(2)

In [26]:
#=========================
#    CLEANIING QUANTITY 
#=========================

In [27]:
df['Quantity'] = np.where((df['Quantity'] < 0) | (df['Quantity'].isnull()), 1.0, df['Quantity'])

In [28]:
df['Quantity'] = df['Quantity'].astype(int)

In [29]:
print(df['Price'].isnull().sum())

0

In [30]:
print(df['Quantity'].isnull().sum())

0

In [31]:
df

     Transaction_ID Product_Name        Price  Quantity        Date
0            1000.0   HEADPHONES   539.187392         4  11/05/2026
1            1001.0   smartphone   299.148021         4  2026-04-03
2            1002.0     charger    126.239849         5  2026-06-21
3            1003.0   SmartWatch   231.696207         8  2026-01-24
4            1004.0   smartphone  1122.517587         5  2026-03-01
..              ...          ...          ...       ...         ...
195          1195.0     charger    668.631629         1  2026-03-25
196          1196.0      Laptop    210.328599         5  2026-05-10
197          1197.0   smartphone   627.117800         2  2026-03-11
198          1198.0   smartphone   627.117800         6  2026-05-25
199          1199.0      Laptop    584.238547         1  2026-05-03

[188 rows x 5 columns]

In [ ]:
'''----- PRODUCT NAME NORMALIZATION -----'''

In [34]:
df['Product_Name'] = df['Product_Name'].str.strip().str.title() # it will remove spaces and format to Title

In [35]:
#----- DATE FORMATING -----

In [36]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce', format='mixed')

In [37]:
df['Date'] = df['Date'].ffill() # replace nan with previous valid value

In [38]:
#-----CREATING NEW FOLDER Total_Sales

In [39]:
df['Total_Sales'] = df['Price'] * df['Quantity']

In [44]:
df['Total_Sales'] = df['Total_Sales'].round(2)

In [45]:
df

     Transaction_ID Product_Name    Price  Quantity       Date  Total_Sales
0            1000.0   Headphones   539.19         4 2026-11-05      2156.75
1            1001.0   Smartphone   299.15         4 2026-04-03      1196.59
2            1002.0      Charger   126.24         5 2026-06-21       631.20
3            1003.0   Smartwatch   231.70         8 2026-01-24      1853.57
4            1004.0   Smartphone  1122.52         5 2026-03-01      5612.59
..              ...          ...      ...       ...        ...          ...
195          1195.0      Charger   668.63         1 2026-03-25       668.63
196          1196.0       Laptop   210.33         5 2026-05-10      1051.64
197          1197.0   Smartphone   627.12         2 2026-03-11      1254.24
198          1198.0   Smartphone   627.12         6 2026-05-25      3762.71
199          1199.0       Laptop   584.24         1 2026-05-03       584.24

[188 rows x 6 columns]

In [46]:
# ----- Managing output----

In [47]:
product_sales = df.groupby('Product_Name')['Total_Sales'].sum().reset_index()

In [49]:
product_sales = product_sales.sort_values(by='Total_Sales', ascending=False)

In [50]:
print(product_sales)

  Product_Name  Total_Sales
1   Headphones    131141.40
4   Smartwatch    125175.39
3   Smartphone    123037.37
2       Laptop    106273.67
0      Charger     76161.95

In [51]:
#======================================
#  LOADING DATA TO SQLITE DATABASE
#======================================

In [54]:
conn = sqlite3.connect('product_sales_data.db') # it will create connection with products_sales_data.db, if not exitst it will create this database

In [55]:
df.to_sql('Cleaned_sales', conn, if_exists='replace', index=False)

188

In [56]:
product_sales.to_sql('products_summary', conn, if_exists='replace', index=False)

5

In [57]:
conn.close()

In [60]:
conn = sqlite3.connect('product_sales_data.db')
db_check = pd.read_sql_query("SELECT * FROM Cleaned_sales", conn)
print(db_check)

     Transaction_ID Product_Name    Price  Quantity                 Date  \
0            1000.0   Headphones   539.19         4  2026-11-05 00:00:00
1            1001.0   Smartphone   299.15         4  2026-04-03 00:00:00
2            1002.0      Charger   126.24         5  2026-06-21 00:00:00
3            1003.0   Smartwatch   231.70         8  2026-01-24 00:00:00
4            1004.0   Smartphone  1122.52         5  2026-03-01 00:00:00
..              ...          ...      ...       ...                  ...
183          1195.0      Charger   668.63         1  2026-03-25 00:00:00
184          1196.0       Laptop   210.33         5  2026-05-10 00:00:00
185          1197.0   Smartphone   627.12         2  2026-03-11 00:00:00
186          1198.0   Smartphone   627.12         6  2026-05-25 00:00:00
187          1199.0       Laptop   584.24         1  2026-05-03 00:00:00

     Total_Sales
0        2156.75
1        1196.59
2         631.20
3        1853.57
4        5612.59
..           ...
183       668.63
184      1051.64
185      1254.24
186      3762.71
187       584.24

[188 rows x 6 columns]